- name: Intro to playbook
  hosts: localhost
  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: Hello
    - name: Print Fruit
      debug:
        msg: Apple
# name is an optional key, but we use always as a best practice
# ansible.builtin.debug is a collection, this is supported from 2.10 version, this is the future
# debug is a module, this is supported only till 2.9 version, it will soon depricate