- name: Play level variables
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

# declaring variables in play level we can access in task level